services:
  prompt-service:
    build:
      context: .
      dockerfile: ./prompt/deployment/Dockerfile
    env_file:
      - ./prompt/.env
    ports:
      - "8000:8000"

  oauth:
    build:
      context: ./oauth
      dockerfile: ./Dockerfile
    env_file:
      - ./oauth/.env
    ports:
      - "3000:3000"
